// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2M5tnMbiyEKIuNFZkBLnRrUNg2db8m0',
    appId: '1:334415828768:web:51a8fd92ebbca4f81d2945',
    messagingSenderId: '334415828768',
    projectId: 'finanzas-931f9',
    authDomain: 'finanzas-931f9.firebaseapp.com',
    storageBucket: 'finanzas-931f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADJSA1vGJ6Epj-O5cuiXDFkYoQRUx-c3E',
    appId: '1:334415828768:android:72f1471e8ca3722e1d2945',
    messagingSenderId: '334415828768',
    projectId: 'finanzas-931f9',
    storageBucket: 'finanzas-931f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAY5cIKcmBOJ7A23Qf9RM2TZ_lJ6dtx3Q',
    appId: '1:334415828768:ios:31eefd177e80899d1d2945',
    messagingSenderId: '334415828768',
    projectId: 'finanzas-931f9',
    storageBucket: 'finanzas-931f9.appspot.com',
    iosBundleId: 'com.example.actividad02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAY5cIKcmBOJ7A23Qf9RM2TZ_lJ6dtx3Q',
    appId: '1:334415828768:ios:31eefd177e80899d1d2945',
    messagingSenderId: '334415828768',
    projectId: 'finanzas-931f9',
    storageBucket: 'finanzas-931f9.appspot.com',
    iosBundleId: 'com.example.actividad02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk2M5tnMbiyEKIuNFZkBLnRrUNg2db8m0',
    appId: '1:334415828768:web:5723f20e53eaf22c1d2945',
    messagingSenderId: '334415828768',
    projectId: 'finanzas-931f9',
    authDomain: 'finanzas-931f9.firebaseapp.com',
    storageBucket: 'finanzas-931f9.appspot.com',
  );
}
